# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node sample.js
    - name: Set git configs
      run: |
        git config --global user.name "shivanibakshimode"
        git config --global user.email "shivani.bakshi@mode.com"
    # - name: update api.md file and push to remote
    #   run: |
    #     git remote set-url origin git@github.com:shivanibakshimode/wiki-demo.wiki.git
    #     git clone git@github.com:shivanibakshimode/wiki-demo.wiki.git
    #     cd wiki-demo.wiki
    #     touch api.md
    #     echo "New file" >> api.md

    #     git add api.md
    #     git commit -m "Updated api.md"
    #     git push

    #     cd ..

    - name: Run repo cloning script
      env: 
        PA_TOKEN: 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
      run: |
        git clone "https://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@github.com/shivanibakshimode/wiki-demo.wiki.git"
        cd wiki-demo.wiki
        touch api.md
        echo "New file" >> api.md
      shell: bash
