name: "Test"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install Deps"
        run: npm install
      - name: "Test"
        run: npx vitest --coverage.enabled true

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  report:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Downlod Artifacts
        uses: actions/download-artifact@v4

      - name: List Files
        run: ls -R

  comment:
    needs: report
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR title
        run: echo "${{ github.event.pull_request.title }}"

      - name: Report Coverage
        shell: bash
        run: |
          value=`cat ./coverage/coverage-summary.json`
          echo The result is $value

      - name: Read Coverage Report
        id: read-report
        run: |
          summaryContent=$(cat ./coverage/coverage-summary.json)
          echo "::set-output name=summaryContent::$summaryContent"

      - name: Create PR Comment
        id: create-comment
        uses: actions/github-script@v5
        with:
          script: |
            const markdownContent = '${{ steps.read-report.outputs.summaryContent }}';

            let markdown = '# Istanbul Coverage Report\n\n';
            Object.keys(markdownContent).forEach(filePath => {
                const fileCoverage = markdownContent[filePath];
                markdown += `## ${filePath}\n\n`;

                Object.keys(fileCoverage["lines"]).forEach((val) => {
                  markdown += `| Total ${val.total} | Covered ${val.covered} | Skipped ${val.skipped} | Percentage ${val.pct} |\n`;
                })

                markdown += '\n';
            });

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: markdown
            })

      # - name: Generate Coverage Report
      #   run: node scripts/parse-coverage.js

      # - name: Add comment to PR
      #   id: create-comment
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       let markdown = '# Istanbul Coverage Report\n\n';
      #       // Loop through each file in the coverage data
      #       Object.keys(coverageData).forEach(filePath => {
      #           const fileCoverage = coverageData[filePath];
      #           markdown += `## ${filePath}\n\n`;

      #           // Loop through each line in the file
      #           fileCoverage.forEach((lineCoverage, lineNumber) => {
      #               const line = lineNumber + 1;
      #               const coveragePercentage = lineCoverage === 0 ? '0%' : '100%';
      #               const status = lineCoverage === 0 ? 'Not covered' : 'Covered';

      #               markdown += `| Line ${line} | ${status} | ${coveragePercentage} |\n`;
      #           });

      #           markdown += '\n';
      #       });
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: markdown
      #       })
