name: "Test Workflow"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Deps
        run: npm install
      - name: Test
        run: npx vitest --coverage.enabled true
      - name: Upload Latest Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-latest
          path: coverage

  report:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      latestSummaryContent: ${{ steps.read-current-report.outputs.latestSummaryContent }}
      previousSummaryContent: ${{ steps.read-previous-report.outputs.previousSummaryContent }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: List Files
        run: ls -R
      - name: Read Previous Coverage Report
        id: read-previous-report
        run: |
          if [ -f "./coverage-previous/coverage-summary.json" ]; then
            previousSummaryContent=$(cat ./coverage-previous/coverage-summary.json)
            # the following lines are only required for multi line json
            previousSummaryContent="${previousSummaryContent//'%'/'%25'}"
            previousSummaryContent="${previousSummaryContent//$'\n'/'%0A'}"
            previousSummaryContent="${previousSummaryContent//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            echo "::set-output name=previousSummaryContent::$previousSummaryContent"
          fi
      - name: Read Latest Coverage Report
        id: read-current-report
        run: |
          latestSummaryContent=$(cat ./coverage-latest/coverage-summary.json)
          # the following lines are only required for multi line json
          latestSummaryContent="${latestSummaryContent//'%'/'%25'}"
          latestSummaryContent="${latestSummaryContent//$'\n'/'%0A'}"
          latestSummaryContent="${latestSummaryContent//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=latestSummaryContent::$latestSummaryContent"
      - name: Copy report
        run: cp -r coverage-latest ./coverage-previous
      - name: Verify current report
        run: ls ./coverage-latest
      - name: Verify previous report
        run: ls ./coverage-previous
      - name: Upload Previous Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-previous
          path: coverage-previous

  comment:
    needs: report
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create PR Comment
        id: create-comment
        uses: actions/github-script@v5
        with:
          script: |
            const latestMarkdownContent = JSON.parse(JSON.stringify(${{ needs.report.outputs.latestSummaryContent }}));
            const previousMarkdownContent = JSON.parse(JSON.stringify(${{ needs.report.outputs.previousSummaryContent }}));
            console.log("previousMarkdownContent: ", previousMarkdownContent);
            console.log("latestMarkdownContent: ", latestMarkdownContent);

            let markdown = '# Code Coverage Report\n\n';
            
            const latestFileCoverage = latestMarkdownContent["total"];
            const previousFileCoverage = previousMarkdownContent["total"];

            markdown += `### Total \n`;

            markdown += '| Statements | Branches | Functions | Lines |';
            markdown += '\n';
            markdown += '| :--------: | :------: | :-------: | :---: |';
            markdown += '\n';

            const latestStatementsParameters = latestFileCoverage["statements"];
            const previousStatementsParameters = previousFileCoverage["statements"];
            
            if(typeof latestStatementsParameters === "object") {
              if(latestStatementsParameters.pct > previousStatementsParameters.pct) {
                markdown += `| **${latestStatementsParameters.pct}%** &nbsp;&#8593; \`${latestStatementsParameters.covered}/${latestStatementsParameters.total - latestStatementsParameters.skipped}\`&nbsp;&nbsp; `;
              } else {
                markdown += `| **${latestStatementsParameters.pct}%** &nbsp;&#8595; \`${latestStatementsParameters.covered}/${latestStatementsParameters.total - latestStatementsParameters.skipped}\`&nbsp;&nbsp; `;
              }
            }

            const branchesParameters = latestFileCoverage["branches"];
            if(typeof branchesParameters === "object") {
              markdown += `| **${branchesParameters.pct}%** &nbsp; \`${branchesParameters.covered}/${branchesParameters.total - branchesParameters.skipped}\`&nbsp;&nbsp; `;
            }
            
            const functionsParameters = latestFileCoverage["functions"];
            if(typeof functionsParameters === "object") {
              markdown += `| **${functionsParameters.pct}%** &nbsp; \`${functionsParameters.covered}/${functionsParameters.total - functionsParameters.skipped}\`&nbsp;&nbsp; `;
            }

            const linesParameters = latestFileCoverage["lines"];
            if(typeof linesParameters === "object") {
              markdown += `| **${linesParameters.pct}%** &nbsp; \`${linesParameters.covered}/${linesParameters.total - linesParameters.skipped}\`&nbsp;&nbsp; `;
            }
            markdown += '\n';

            markdown += `<details>\n`;
            markdown += '<summary>\n\n### View Additional Reports\n\n</summary>\n\n';

            markdown += '| File  | Statements | Branches | Functions | Lines |';
            markdown += '\n';
            markdown += '| :---: | :--------: | :------: | :-------: | :---: |';
            markdown += '\n';

            Object.keys(latestMarkdownContent).forEach((filePath) => {
                const latestFileCoverage = latestMarkdownContent[filePath];

                const fileName = filePath.split(context.repo.repo).pop();
                if(fileName !== "total") {
                  markdown += `| ${fileName} `;

                  const statementsParameters = latestFileCoverage["statements"];
                  if(typeof statementsParameters === "object") {
                    markdown += `| **${statementsParameters.pct}%**   \`${statementsParameters.covered}/${statementsParameters.total - statementsParameters.skipped}\` `;
                  }

                  const branchesParameters = latestFileCoverage["branches"];
                  if(typeof branchesParameters === "object") {
                    markdown += `| **${branchesParameters.pct}%**   \`${branchesParameters.covered}/${branchesParameters.total - branchesParameters.skipped}\` `;
                  }
                  
                  const functionsParameters = latestFileCoverage["functions"];
                  if(typeof functionsParameters === "object") {
                    markdown += `| **${functionsParameters.pct}%**   \`${functionsParameters.covered}/${functionsParameters.total - functionsParameters.skipped}\` `;
                  }

                  const linesParameters = latestFileCoverage["lines"];
                  if(typeof linesParameters === "object") {
                    markdown += `| **${linesParameters.pct}%**   \`${linesParameters.covered}/${linesParameters.total - linesParameters.skipped}\` `;
                  }

                  markdown += '\n';
                }
            });
            markdown += `</details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: markdown
            })

